config/routes.rb
Ujs::Application.routes.draw do

  resources :people do
    resources :cats
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :admin, :name
  has_many :cats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :find_person
  before_filter :find_cat, :only => [:show, :destroy]
  def new
    @cat = @person.cats.build
    @submit_label = "Create"
    respond_to do |format|
      format.html
      format.js { }
    end
  end
  def destroy
    @cat.destroy
    flash[:notice] = "Cat has been deleted."
    redirect_to @person
  end
  def create
    @cat = @person.cats.build(params[:cat])
    if @cat.save
      flash[:notice] = "Cat has been created."
      redirect_to @person
    else
      flash[:alert] = "Cat has not been created."
      render :action => "new"
    end
  end
  def show
  end
private
  def find_person
    @person = Person.find(params[:person_id])
  end
  def find_cat
    @cat = @person.cats.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = params[:admin] ? Person.where(:admin => true) : Person.all
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
    end
  end
  def show
    @person = Person.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_new.html.erb
<h2>New Cat</h2>
<%= form_for [@person, @cat] do |f| %>
<%= f.submit "Submit", %>
<% end %>
<%= link_to "Cancel", @person %>

app/views/cats/new.html.erb
<%= render :partial => 'new' %>

app/views/cats/new.js.erb
$('#<%= dom_id(@cat) %> .details').html('<%= escape_javascript render(:partial => "new") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ujs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_person.html.erb
<li><%= link_to person.name, person %></li>

app/views/people/index.html.erb
<%= link_to "Showing all (toggle)", people_path(:admin => true), :remote => true, :id => 'toggle' %>
<ul id='people'>
  <%= render @people %>
</ul>

app/views/people/index.js.erb
<% link_text = params[:admin] ? "Admins" : "All" %>
<% href = params[:admin] ? people_path : people_path(:admin => true) %>
$("#toggle").html("Displaying <%= link_text %> (toggle)");
$("#toggle").attr("href", "<%= href %>");
$("#people").html('<%= escape_javascript(render @people) %>');

app/views/people/show.html.erb
<h2><%= @person %></h2>
<% if @person.cats.size == 0 %>
<h5>No Cats</h5>
<% else %>
<h4>Cats</h4>
<% @person.cats.each do |cat| %>
<li>
<%= link_to "One Cat", [@person, cat] %>
</li>
<% end %>
</ul>
<% end %>

<%= link_to "New Cat", new_person_cat_path(@person), :remote => true %>